import { QuizSet } from './quiz-types';

export const DEFAULT_QUIZ_SETS: QuizSet[] = [
  // ─── 1. Altes Testament ──────────────────────────────────────────────────
  {
    id: 'default-at-1',
    title: 'Altes Testament – Klassiker',
    category: 'AT',
    description: 'Die bekanntesten Geschichten von Adam bis Daniel',
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
    questions: [
      {
        id: 'at-q1',
        text: 'Was war die zehnte und letzte Plage in Ägypten?',
        answers: ['Tod der Erstgeburt', 'Finsternis über Ägypten', 'Heuschrecken', 'Hagel und Feuer'],
        correct: 0,
        timeLimit: 20,
        explanation: '2. Mose 12 – Der Tod aller Erstgeborenen in Ägypten war die letzte und schlimmste Plage, die Pharao zur Freilassung Israels zwang.',
      },
      {
        id: 'at-q2',
        text: 'Wie lange war Noahs Arche auf dem Wasser, bevor sie auf einem Berg aufsetzte?',
        answers: ['40 Tage', '100 Tage', '150 Tage', '365 Tage'],
        correct: 2,
        timeLimit: 25,
        explanation: '1. Mose 7,24 – Die Wasser standen 150 Tage hoch über der Erde, bevor sie zurückgingen.',
      },
      {
        id: 'at-q3',
        text: 'Womit erschlug David den Riesen Goliat, bevor er ihm das Haupt abschlug?',
        answers: ['Mit einem Speer', 'Mit einem Stein aus der Schleuder', 'Mit einer Keule', 'Mit einem Schwert'],
        correct: 1,
        timeLimit: 15,
        explanation: '1. Samuel 17,49 – David schleuderte einen Stein, der Goliat an der Stirn traf und ihn zu Boden warf.',
      },
      {
        id: 'at-q4',
        text: 'Auf welchem Berg empfing Mose die Zehn Gebote?',
        answers: ['Berg Karmel', 'Berg Nebo', 'Berg Sinai', 'Berg Tabor'],
        correct: 2,
        timeLimit: 15,
        explanation: '2. Mose 19–20 – Auf dem Berg Sinai (auch Horeb genannt) erschien Gott Mose und gab ihm die Gebote.',
      },
      {
        id: 'at-q5',
        text: 'Welches Tier sprach in der Bibel zu Bileam und rettete ihm damit das Leben?',
        answers: ['Ein Rabe', 'Eine Schlange', 'Eine Eselin', 'Ein Löwe'],
        correct: 2,
        timeLimit: 20,
        explanation: '4. Mose 22,28 – Gottes Engel versperrte den Weg, und Gott öffnete der Eselin den Mund, sodass sie mit Bileam sprach.',
      },
      {
        id: 'at-q6',
        text: 'Wer versteckte die zwei Späher Josuas in Jericho und rettete damit ihr Leben?',
        answers: ['Debora', 'Rahab', 'Rut', 'Hanna'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Josua 2 – Rahab, eine Gastwirtin in Jericho, verbarg die Späher auf ihrem Dach und ließ sie durch ein rotes Seil am Fenster entkommen.',
      },
      {
        id: 'at-q7',
        text: 'Was verlor Simson seine übernatürliche Kraft, als Delila es abschneiden ließ?',
        answers: ['Seinen Gürtel', 'Seine Haare', 'Seinen Mantel', 'Seinen Bart'],
        correct: 1,
        timeLimit: 15,
        explanation: 'Richter 16,17 – Simson verriet Delila, dass sein langes Haar das Zeichen seines Nasiräer-Gelübdes war und ihm die Kraft gab.',
      },
      {
        id: 'at-q8',
        text: 'Welchen König salbte Samuel als ersten König Israels?',
        answers: ['David', 'Salomo', 'Saul', 'Isbaal'],
        correct: 2,
        timeLimit: 20,
        explanation: '1. Samuel 10,1 – Samuel salbte Saul, den Sohn Kis aus dem Stamm Benjamin, zum ersten König Israels.',
      },
      {
        id: 'at-q9',
        text: 'Mit wem schloss Gott den ersten Bund, besiegelt durch das Zeichen der Beschneidung?',
        answers: ['Mit Mose', 'Mit Noah', 'Mit Abraham', 'Mit Isaak'],
        correct: 2,
        timeLimit: 20,
        explanation: '1. Mose 17 – Gott schloss mit Abraham einen ewigen Bund und gab die Beschneidung als Bundeszeichen.',
      },
    ],
  },

  // ─── 2. Neues Testament ───────────────────────────────────────────────────
  {
    id: 'default-nt-1',
    title: 'Neues Testament – Grundlagen',
    category: 'NT',
    description: 'Von der Geburt Jesu bis zur Apostelgeschichte',
    createdAt: 1700000001000,
    updatedAt: 1700000001000,
    questions: [
      {
        id: 'nt-q1',
        text: 'Welcher Engel verkündigte Maria die Geburt Jesu?',
        answers: ['Michael', 'Rafael', 'Gabriel', 'Uriel'],
        correct: 2,
        timeLimit: 15,
        explanation: 'Lukas 1,26 – Der Engel Gabriel wurde von Gott gesandt, um Maria die Empfängnis des Sohnes Gottes zu verkünden.',
      },
      {
        id: 'nt-q2',
        text: 'Wie alt war Jesus, als er zum ersten Mal im Tempel lehrte und die Schriftgelehrten erstaunte?',
        answers: ['10 Jahre', '12 Jahre', '15 Jahre', '18 Jahre'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Lukas 2,42 – Mit zwölf Jahren blieb Jesus in Jerusalem und saß mitten unter den Lehrern, hörte ihnen zu und stellte Fragen.',
      },
      {
        id: 'nt-q3',
        text: 'Was antwortete Jesus dem Teufel auf die erste Versuchung in der Wüste?',
        answers: ['"Geh weg von mir, Satan!"', '"Der Mensch lebt nicht vom Brot allein."', '"Bete den Herrn an!"', '"Du sollst Gott nicht versuchen."'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Matthäus 4,4 – Als der Teufel Jesus aufforderte, Steine in Brot zu verwandeln, zitierte Jesus 5. Mose 8,3.',
      },
      {
        id: 'nt-q4',
        text: 'Welches Evangelium enthält keine Gleichnisse Jesu?',
        answers: ['Matthäus', 'Markus', 'Lukas', 'Johannes'],
        correct: 3,
        timeLimit: 25,
        explanation: 'Das Johannesevangelium enthält keine Gleichnisse im klassischen Sinne – stattdessen verwendet Johannes lange Reden und Bildreden Jesu ("Ich bin die Tür", "Ich bin der Weinstock").',
      },
      {
        id: 'nt-q5',
        text: 'Für wie viele Silberstücke verriet Judas Jesus an die Hohenpriester?',
        answers: ['10', '20', '30', '50'],
        correct: 2,
        timeLimit: 15,
        explanation: 'Matthäus 26,15 – Judas einigte sich auf 30 Silberstücke – die Summe, die nach 2. Mose 21,32 für einen getöteten Sklaven bezahlt wurde.',
      },
      {
        id: 'nt-q6',
        text: 'Was passierte beim Tod Jesu am Kreuz mit dem Vorhang im Tempel?',
        answers: ['Er fing Feuer', 'Er zerriss von oben bis unten', 'Er wurde schwarz', 'Er verschwand'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Matthäus 27,51 – Der Vorhang im Tempel, der das Allerheiligste abtrennte, zerriss von oben bis unten – ein Zeichen, dass der Weg zu Gott nun für alle offen ist.',
      },
      {
        id: 'nt-q7',
        text: 'Wem erschien der auferstandene Jesus als erstem Mal?',
        answers: ['Petrus', 'Johannes', 'Maria Magdalena', 'Den elf Jüngern'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Johannes 20,14-16 – Maria Magdalena war die Erste, der Jesus nach seiner Auferstehung erschien. Sie erkannte ihn erst, als er sie beim Namen rief.',
      },
      {
        id: 'nt-q8',
        text: 'Was war das Zeichen, an dem die zwei Emmaus-Jünger Jesus erkannten?',
        answers: ['Seine Stimme', 'Das Brechen des Brotes', 'Seine Wunden', 'Sein Gebet'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Lukas 24,30-31 – Als Jesus mit ihnen am Tisch das Brot brach und dankte, gingen ihnen die Augen auf und sie erkannten ihn.',
      },
    ],
  },

  // ─── 3. Gleichnisse ───────────────────────────────────────────────────────
  {
    id: 'default-gleichnisse-1',
    title: 'Gleichnisse Jesu',
    category: 'Evangelien',
    description: 'Die tiefgründigen Lehrgeschichten des Meisters',
    createdAt: 1700000002000,
    updatedAt: 1700000002000,
    questions: [
      {
        id: 'gl-q1',
        text: 'Im Gleichnis vom verlorenen Sohn – was tat der Vater, als er seinen Sohn von Weitem kommen sah?',
        answers: ['Er schloss die Tür', 'Er schickte einen Knecht entgegen', 'Er lief ihm entgegen und fiel ihm um den Hals', 'Er wartete auf der Schwelle'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Lukas 15,20 – Der Vater lief seinem Sohn entgegen, fiel ihm um den Hals und küsste ihn – ein Bild für Gottes bedingungslose Gnade.',
      },
      {
        id: 'gl-q2',
        text: 'Was machte der barmherzige Samariter als Erstes, nachdem er den verletzten Mann fand?',
        answers: ['Er holte Hilfe', 'Er verband seine Wunden und goss Öl und Wein darauf', 'Er trug ihn sofort zum Wirt', 'Er betete über ihm'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Lukas 10,34 – Er trat hinzu, verband seine Wunden und goss Öl und Wein darauf – beides waren damals gängige Heilmittel.',
      },
      {
        id: 'gl-q3',
        text: 'Im Gleichnis vom Sämann – was bedeutet der Same, der unter Dornen fiel?',
        answers: ['Menschen ohne Verständnis', 'Menschen ohne Wurzel, die in Versuchung fallen', 'Menschen, die durch Sorgen und Reichtum erstickt werden', 'Menschen, die reiche Frucht bringen'],
        correct: 2,
        timeLimit: 25,
        explanation: 'Matthäus 13,22 – Die Dornen stehen für die Sorgen der Welt und den Betrug des Reichtums, die das Wort ersticken.',
      },
      {
        id: 'gl-q4',
        text: 'Im Gleichnis von den Talenten – was sagte der Herr zum Diener mit den fünf Talenten?',
        answers: ['"Du hast gut gewirtschaftet."', '"Geh ein in die Freude deines Herrn!"', '"Ich belohne deine Treue."', '"Behalte alles für dich."'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Matthäus 25,21 – "Gut, du treuer und kluger Knecht! Geh ein in die Freude deines Herrn!" – Wer im Kleinen treu ist, dem wird mehr anvertraut.',
      },
      {
        id: 'gl-q5',
        text: 'Im Gleichnis vom Weinberg – zu welcher Zeit des Tages wurden noch Arbeiter eingestellt, die dennoch den vollen Tageslohn bekamen?',
        answers: ['Zur dritten Stunde', 'Zur sechsten Stunde', 'Zur neunten Stunde', 'Zur elften Stunde'],
        correct: 3,
        timeLimit: 25,
        explanation: 'Matthäus 20,6-9 – Auch die Arbeiter der elften Stunde (kurz vor Feierabend) erhielten den vollen Lohn – ein Bild für Gottes großzügige Gnade.',
      },
      {
        id: 'gl-q6',
        text: 'Im Gleichnis vom reichen Mann und dem armen Lazarus – wohin kam Lazarus nach seinem Tod?',
        answers: ['In den Hades', 'In Abrahams Schoß', 'Ins Paradies', 'In den Himmel'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Lukas 16,22 – Der arme Lazarus wurde von Engeln in Abrahams Schoß getragen, ein Bild für den Ort der Ruhe und Seligkeit.',
      },
      {
        id: 'gl-q7',
        text: 'Was suchte die Frau im Gleichnis von der verlorenen Münze so ausdauernd?',
        answers: ['Ihre goldene Kette', 'Eine von zehn Silbermünzen', 'Ihren Ehering', 'Eine von sieben Goldmünzen'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Lukas 15,8 – Die Frau hatte zehn Silbermünzen und verlor eine. Sie zündete ein Licht an, fegte das ganze Haus und suchte sorgfältig.',
      },
      {
        id: 'gl-q8',
        text: 'Im Gleichnis vom ungerechten Richter – was erreichte die Witwe durch ihr ausdauerndes Bitten?',
        answers: ['Geld als Entschädigung', 'Ihr Recht gegen ihren Widersacher', 'Einen neuen Richter', 'Frieden mit ihrem Feind'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Lukas 18,3-5 – Der Richter half ihr schliesslich, nicht aus Gerechtigkeit, sondern weil sie ihn mit ihrem Bitten ermüdete. Jesus lehrt damit ausdauerndes Gebet.',
      },
    ],
  },

  // ─── 4. Psalmen ───────────────────────────────────────────────────────────
  {
    id: 'default-psalmen-1',
    title: 'Psalmen & Weisheit',
    category: 'Psalmen',
    description: 'Tiefe Verse aus den Psalmen, Sprüchen und Predigerbuch',
    createdAt: 1700000003000,
    updatedAt: 1700000003000,
    questions: [
      {
        id: 'ps-q1',
        text: 'Wie lautet der vollständige erste Vers von Psalm 23?',
        answers: ['"Der HERR ist mein Licht und mein Heil."', '"Der HERR ist mein Hirte, mir wird nichts mangeln."', '"Der HERR ist meine Zuflucht und meine Stärke."', '"Der HERR ist mein Fels und mein Retter."'],
        correct: 1,
        timeLimit: 15,
        explanation: 'Psalm 23,1 – Dieser Psalm Davids ist einer der bekanntesten der ganzen Bibel und beschreibt Gottes fürsorgliche Führung.',
      },
      {
        id: 'ps-q2',
        text: 'Was sagt Psalm 139 darüber, wohin man vor Gott fliehen kann?',
        answers: ['Man kann im Gebet zu ihm fliehen', 'Man kann nirgends vor ihm fliehen', 'Man kann in der Tiefe der Erde vor ihm fliehen', 'Man kann in der Stille vor ihm fliehen'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Psalm 139,7-10 – "Wohin könnte ich fliehen vor deinem Geist? ... Steige ich hinauf in den Himmel, so bist du da. Bette ich mich in die Unterwelt, du bist da."',
      },
      {
        id: 'ps-q3',
        text: 'Welcher Psalm beginnt mit den Worten, die Jesus am Kreuz sprach: "Mein Gott, mein Gott, warum hast du mich verlassen?"',
        answers: ['Psalm 22', 'Psalm 31', 'Psalm 42', 'Psalm 69'],
        correct: 0,
        timeLimit: 20,
        explanation: 'Psalm 22,2 – Dieser klagende Psalm Davids beginnt mit den genauen Worten, die Jesus am Kreuz zitierte (Matthäus 27,46).',
      },
      {
        id: 'ps-q4',
        text: 'Was ist laut Sprüche 9,10 der Anfang der Weisheit?',
        answers: ['Demut vor den Menschen', 'Die Furcht des HERRN', 'Das Studium der Schrift', 'Die Liebe zum Nächsten'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Sprüche 9,10 – "Die Furcht des HERRN ist der Anfang der Weisheit, und den Heiligen erkennen ist Verstand."',
      },
      {
        id: 'ps-q5',
        text: 'In welchem Psalm betet David nach seinem Ehebruch mit Batseba um Vergebung?',
        answers: ['Psalm 32', 'Psalm 38', 'Psalm 51', 'Psalm 103'],
        correct: 2,
        timeLimit: 25,
        explanation: 'Psalm 51 – "Schaffe in mir, Gott, ein reines Herz" – dieser tiefe Bußpsalm entstand laut Überschrift nach Nathans Konfrontation mit David.',
      },
      {
        id: 'ps-q6',
        text: 'Was verkündet Psalm 19,2 über die Natur?',
        answers: ['"Die Erde ist des HERRN."', '"Die Himmel erzählen die Herrlichkeit Gottes."', '"Der Wald jubelt vor dem HERRN."', '"Alle Berge und Hügel sollen loben."'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Psalm 19,2 – "Die Himmel erzählen die Herrlichkeit Gottes, und das Firmament verkündigt das Werk seiner Hände."',
      },
      {
        id: 'ps-q7',
        text: 'Was sagt Prediger 12,13 als letztes Fazit des ganzen Buches?',
        answers: ['"Alles ist Eitelkeit."', '"Fürchte Gott und halte seine Gebote."', '"Es gibt nichts Neues unter der Sonne."', '"Iss, trink und freue dich."'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Prediger 12,13 – Nach allem Nachdenken lautet das Fazit: "Fürchte Gott und halte seine Gebote, denn das gilt für alle Menschen."',
      },
    ],
  },

  // ─── 5. Propheten ────────────────────────────────────────────────────────
  {
    id: 'default-propheten-1',
    title: 'Die Propheten',
    category: 'Propheten',
    description: 'Gottes Botschafter und ihre Verkündigungen',
    createdAt: 1700000004000,
    updatedAt: 1700000004000,
    questions: [
      {
        id: 'pr-q1',
        text: 'Welcher Prophet trat dem König Ahab entgegen und verkündete eine dreijährige Dürre?',
        answers: ['Elisa', 'Elia', 'Amos', 'Micha'],
        correct: 1,
        timeLimit: 20,
        explanation: '1. Könige 17,1 – Elia der Tischbiter sagte König Ahab: "So wahr der HERR lebt – es wird diese Jahre weder Tau noch Regen geben, außer auf mein Wort."',
      },
      {
        id: 'pr-q2',
        text: 'Welche Stadt wurde durch die Predigt des Propheten Jona zur Umkehr bewegt?',
        answers: ['Babel', 'Ninive', 'Tyrus', 'Sidon'],
        correct: 1,
        timeLimit: 15,
        explanation: 'Jona 3 – Die ganze Stadt Ninive, einschliesslich des Königs, fastete und rief zu Gott – und Gott verschonte die Stadt.',
      },
      {
        id: 'pr-q3',
        text: 'Was berührte die Lippen des Propheten Jesaja bei seiner Berufungsvision?',
        answers: ['Die Hand Gottes', 'Eine glühende Kohle vom Altar', 'Ein Cherub mit einem Schwert', 'Ein weisses Tuch'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Jesaja 6,6-7 – Ein Seraph flog zu Jesaja mit einer glühenden Kohle vom Altar und berührte damit seinen Mund: "Deine Schuld ist getilgt."',
      },
      {
        id: 'pr-q4',
        text: 'Jeremia wird oft als "weinender Prophet" bezeichnet. Warum wurde er gefangen genommen?',
        answers: ['Weil er den König beleidigte', 'Weil er Desertion predigte und zur Kapitulation aufrief', 'Weil er falsch prophezeite', 'Weil er den Tempel befleckte'],
        correct: 1,
        timeLimit: 25,
        explanation: 'Jeremia 38,4 – Die Fürsten sagten: "Dieser Mann muss sterben, denn er entmutigt die Krieger." Jeremia hatte zur Übergabe an Babel aufgerufen.',
      },
      {
        id: 'pr-q5',
        text: 'Was sah Hesekiel in seiner bekanntesten Vision neben dem Fluss Kebar?',
        answers: ['Einen Regenbogen über dem Thron Gottes', 'Vier lebende Wesen und ein Rad im Rad', 'Verdorrte Knochen in einem Tal', 'Sieben Leuchter aus Gold'],
        correct: 1,
        timeLimit: 25,
        explanation: 'Hesekiel 1 – Die Thronwagenvision mit vier Lebewesen (Mensch, Löwe, Stier, Adler) und Rädern voller Augen ist eine der eindrücklichsten Visionen der Bibel.',
      },
      {
        id: 'pr-q6',
        text: 'Welcher Prophet verkündigte die Verheissung: "Sie werden zu Pflugscharen ihre Schwerter schmieden"?',
        answers: ['Jeremia', 'Jesaja', 'Micha', 'Beide – Jesaja und Micha'],
        correct: 3,
        timeLimit: 25,
        explanation: 'Jesaja 2,4 und Micha 4,3 – Beide Propheten überliefern diese Friedensvision in fast identischen Worten – ein Zeichen ihrer gemeinsamen prophetischen Überlieferung.',
      },
      {
        id: 'pr-q7',
        text: 'Welcher Prophet verkündigte: "Ich will euch ein neues Herz geben und einen neuen Geist in euch legen"?',
        answers: ['Jesaja', 'Jeremia', 'Hesekiel', 'Daniel'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Hesekiel 36,26 – Diese Verheissung des neuen Herzens ist eine der bedeutendsten messianischen Weissagungen des Alten Testaments.',
      },
    ],
  },

  // ─── 6. Paulus ────────────────────────────────────────────────────────────
  {
    id: 'default-paulus-1',
    title: 'Paulus – Der Völkerapostel',
    category: 'Paulus',
    description: 'Leben, Briefe und Theologie des Apostels Paulus',
    createdAt: 1700000005000,
    updatedAt: 1700000005000,
    questions: [
      {
        id: 'pau-q1',
        text: 'Was war Paulus von Beruf, bevor er Missionar wurde?',
        answers: ['Fischer', 'Zimmermann', 'Zeltmacher', 'Schreiber'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Apostelgeschichte 18,3 – Paulus, Aquila und Priszilla arbeiteten als Zeltmacher. Paulus finanzierte seine Missionsarbeit oft durch diesen Beruf.',
      },
      {
        id: 'pau-q2',
        text: 'An welche Gemeinde schrieb Paulus das berühmte "Hohelied der Liebe" (Kapitel 13)?',
        answers: ['Römer', 'Galater', '1. Korinther', 'Epheser'],
        correct: 2,
        timeLimit: 15,
        explanation: '1. Korinther 13 – Paulus schrieb dieses Kapitel als Antwort auf Streitigkeiten in der korinthischen Gemeinde über geistliche Gaben.',
      },
      {
        id: 'pau-q3',
        text: 'Was meint Paulus mit "Rechtfertigung aus Glauben" im Römerbrief?',
        answers: ['Gott belohnt gute Werke', 'Gott erklärt den Sünder um des Glaubens an Christus willen für gerecht', 'Glaube ersetzt die Moral', 'Jeder wird am Ende gerettet'],
        correct: 1,
        timeLimit: 25,
        explanation: 'Römer 3,28 – "So halten wir nun dafür, dass der Mensch gerecht wird durch den Glauben, ohne Werke des Gesetzes." Dies war Luthers Schlüsselvers für die Reformation.',
      },
      {
        id: 'pau-q4',
        text: 'Wie beschreibt Paulus die "Rüstung Gottes" in Epheser 6? Was ist das Schwert des Geistes?',
        answers: ['Das Gebet', 'Das Wort Gottes', 'Der Glaube', 'Die Liebe'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Epheser 6,17 – "... und das Schwert des Geistes, welches ist das Wort Gottes." Das Wort Gottes ist das einzige offensive Angriffsmittel in der Rüstung.',
      },
      {
        id: 'pau-q5',
        text: 'Was sagt Paulus in Philipper 4,7 über den "Frieden Gottes"?',
        answers: ['Er kommt nach dem Tod', 'Er übersteigt allen Verstand', 'Er gehört nur den Vollkommenen', 'Er kommt durch gute Werke'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Philipper 4,7 – "Und der Friede Gottes, der allen Verstand übersteigt, wird eure Herzen und Sinne bewahren in Christus Jesus."',
      },
      {
        id: 'pau-q6',
        text: 'Welcher Mitarbeiter verliess Paulus, "weil er die gegenwärtige Welt lieb gewonnen hatte"?',
        answers: ['Barnabas', 'Silas', 'Demas', 'Titus'],
        correct: 2,
        timeLimit: 25,
        explanation: '2. Timotheus 4,10 – "Demas hat mich verlassen; er hat die gegenwärtige Welt lieb gewonnen." Ein trauriges Zeugnis über einen einstigen Mitarbeiter.',
      },
      {
        id: 'pau-q7',
        text: 'Was nennt Paulus in Galater 5,22 als erste Frucht des Heiligen Geistes?',
        answers: ['Freude', 'Glaube', 'Friede', 'Liebe'],
        correct: 3,
        timeLimit: 15,
        explanation: 'Galater 5,22 – "Die Frucht des Geistes aber ist: Liebe, Freude, Friede, Langmut, Freundlichkeit, Güte, Treue, Sanftmut, Keuschheit."',
      },
    ],
  },

  // ─── 7. Wunder Jesu ───────────────────────────────────────────────────────
  {
    id: 'default-wunder-1',
    title: 'Wunder Jesu',
    category: 'Evangelien',
    description: 'Die Zeichen und Wunder, die Jesus tat',
    createdAt: 1700000006000,
    updatedAt: 1700000006000,
    questions: [
      {
        id: 'wu-q1',
        text: 'Was sprach Jesus zum Gelähmten am Teich Betesda, bevor er ihn heilte?',
        answers: ['"Steh auf und sündige nicht mehr."', '"Willst du gesund werden?"', '"Dein Glaube hat dir geholfen."', '"Deine Sünden sind dir vergeben."'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Johannes 5,6 – Jesus fragte ihn: "Willst du gesund werden?" – Der Mann hatte 38 Jahre auf Heilung gewartet.',
      },
      {
        id: 'wu-q2',
        text: 'Was geschah, als Petrus auf Jesu Geheiß über das Wasser gehen wollte?',
        answers: ['Er lief souverän zu Jesus', 'Er sank, als er auf den Wind schaute', 'Er weigerte sich, das Schiff zu verlassen', 'Er schwamm zu Jesus'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Matthäus 14,30 – Als Petrus auf den Wind sah, erschrak er und begann zu sinken. Er rief: "Herr, rette mich!" – und Jesus griff sofort nach ihm.',
      },
      {
        id: 'wu-q3',
        text: 'Wie viele Körbe mit Resten wurden nach der Speisung der 5.000 eingesammelt?',
        answers: ['5', '7', '12', '24'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Matthäus 14,20 – Es wurden zwölf Körbe voll Brocken gesammelt – so viele, wie es Stämme Israels gab. Ein Zeichen für den Überfluss in Gottes Reich.',
      },
      {
        id: 'wu-q4',
        text: 'Was rief Jesus, als er Lazarus aus dem Grab rief?',
        answers: ['"Lazarus, steh auf!"', '"Lazarus, komm heraus!"', '"Lazarus, lebe!"', '"Lazarus, ich rufe dich!"'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Johannes 11,43 – Jesus rief mit lauter Stimme: "Lazarus, komm heraus!" Und der Verstorbene kam heraus, noch mit Tüchern umwickelt.',
      },
      {
        id: 'wu-q5',
        text: 'Welchen Satz sprach Jesus, bevor er den Sturm auf dem See stillt?',
        answers: ['Er betete zuerst', '"Im Namen des Vaters!"', '"Schweig, sei still!"', '"Friede sei mit euch!"'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Markus 4,39 – Jesus "bedrohte" den Wind und sprach zum See: "Schweig, sei still!" Sofort legte sich der Wind und es wurde völlig still.',
      },
      {
        id: 'wu-q6',
        text: 'Was sagte der Hauptmann von Kapernaum zu Jesus, das ihn so tief beeindruckte?',
        answers: ['"Du bist der Sohn Gottes!"', '"Ich bin nicht würdig, dass du unter mein Dach gehst."', '"Heile meinen Knecht."', '"Sprich nur ein Wort!"'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Matthäus 8,8 – Der Hauptmann sagte: "Herr, ich bin nicht würdig, dass du unter mein Dach gehst; sprich nur ein Wort, so wird mein Knecht gesund." Jesus staunte: "Solchen Glauben habe ich in Israel nicht gefunden."',
      },
      {
        id: 'wu-q7',
        text: 'Was tat Jesus mit Speichel, bevor er einen Blinden in Betsaida heilte?',
        answers: ['Er salbte seine Augen mit Öl', 'Er strich Speichel auf seine Augen und legte die Hände auf', 'Er sprach ein Wort der Heilung', 'Er wusch seine Augen mit Wasser'],
        correct: 1,
        timeLimit: 25,
        explanation: 'Markus 8,23 – Jesus strich Speichel auf die Augen des Blinden und legte ihm die Hände auf. Die Heilung geschah in zwei Phasen – zuerst sah er verschwommen, dann klar.',
      },
    ],
  },

  // ─── 8. Schöpfung & Erzväter ─────────────────────────────────────────────
  {
    id: 'default-schoepfung-1',
    title: 'Schöpfung & Erzväter',
    category: 'AT',
    description: '1. Mose: Von der Erschaffung der Welt bis zu Josef in Ägypten',
    createdAt: 1700000007000,
    updatedAt: 1700000007000,
    questions: [
      {
        id: 'sc-q1',
        text: 'Was erschuf Gott am siebten Tag der Schöpfung?',
        answers: ['Die Sterne und Planeten', 'Die Tiere des Meeres', 'Nichts – er ruhte und heiligte den Tag', 'Den Menschen'],
        correct: 2,
        timeLimit: 15,
        explanation: '1. Mose 2,2-3 – Am siebten Tag ruhte Gott von all seinem Werk und segnete diesen Tag und heiligte ihn – Grundlage des Sabbats.',
      },
      {
        id: 'sc-q2',
        text: 'Warum erschlug Kain seinen Bruder Abel?',
        answers: ['Wegen Land und Besitz', 'Weil Abel beliebter beim Vater war', 'Weil Gott Abels Opfer, aber nicht seines annahm', 'Wegen eines Streites um Wasser'],
        correct: 2,
        timeLimit: 20,
        explanation: '1. Mose 4,5 – Gott sah Abels Opfer an, Kains aber nicht. Kain wurde zornig. Gott warnte ihn: "Die Sünde lauert vor der Tür" – doch Kain hörte nicht.',
      },
      {
        id: 'sc-q3',
        text: 'Wo landete die Arche Noah nach der Flut?',
        answers: ['Auf dem Berg Hermon', 'Auf dem Berg Sinai', 'Auf dem Ararat', 'Auf dem Ölberg'],
        correct: 2,
        timeLimit: 20,
        explanation: '1. Mose 8,4 – "Die Arche liess sich nieder auf dem Gebirge Ararat" – heute in der Türkei/Armenien.',
      },
      {
        id: 'sc-q4',
        text: 'Was prüfte Gott, als er Abraham befahl, Isaak zu opfern?',
        answers: ['Seine Geduld', 'Seinen Gehorsam und sein Vertrauen', 'Sein Wissen um Gottes Gebote', 'Seine Liebe zu Isaak'],
        correct: 1,
        timeLimit: 20,
        explanation: '1. Mose 22,1 – "Danach prüfte Gott Abraham." Als Abraham bereit war zu gehorchen, griff Gott ein: "Nun weiss ich, dass du Gott fürchtest."',
      },
      {
        id: 'sc-q5',
        text: 'Wie hiess der Ort, wo Jakob mit einem Gottesmann rang und einen neuen Namen erhielt?',
        answers: ['Bethel', 'Peniel', 'Sichem', 'Beerscheba'],
        correct: 1,
        timeLimit: 25,
        explanation: '1. Mose 32,31 – Jakob nannte den Ort "Peniel" (Angesicht Gottes): "Denn ich habe Gott von Angesicht gesehen und mein Leben wurde gerettet." Sein neuer Name: Israel.',
      },
      {
        id: 'sc-q6',
        text: 'Was deutete Josef im Gefängnis, das wenig später in Erfüllung ging?',
        answers: ['Das Traumgesicht des Pharaos', 'Die Träume des Mundschenks und des Bäckers', 'Die Sterne in seinem Traum', 'Das Traumgesicht seines Vaters'],
        correct: 1,
        timeLimit: 20,
        explanation: '1. Mose 40 – Der Mundschenk wurde nach drei Tagen wieder eingesetzt (wie Josef deutete), der Bäcker hingegen hingerichtet. Doch der Mundschenk vergass Josef zunächst.',
      },
      {
        id: 'sc-q7',
        text: 'Warum konnte Josefs Familie nach Ägypten kommen und überleben?',
        answers: ['Weil Josef Pharaos Ratgeber wurde', 'Weil Josef die sieben fetten und sieben mageren Jahre gedeutet hatte und Vorräte angelegt wurden', 'Weil Ägypten ein Bündnis mit Israel schloss', 'Weil Josef seinen Brüdern vergab'],
        correct: 1,
        timeLimit: 20,
        explanation: '1. Mose 41 – Josef deutete Pharaos Träume: 7 Jahre Überfluss, dann 7 Jahre Hunger. Pharao machte ihn zum Statthalter, und Josef legte Vorräte an – die die ganze Region retteten.',
      },
    ],
  },

  // ─── 9. Apostelgeschichte ─────────────────────────────────────────────────
  {
    id: 'default-apostel-1',
    title: 'Apostelgeschichte',
    category: 'NT',
    description: 'Die Ausbreitung der frühen Kirche durch die Kraft des Geistes',
    createdAt: 1700000008000,
    updatedAt: 1700000008000,
    questions: [
      {
        id: 'ap-q1',
        text: 'Was geschah den Jüngern sichtbar am ersten Pfingstfest?',
        answers: ['Ein helles Licht erschien', 'Feuerzungen setzten sich auf jeden von ihnen', 'Eine Wolke erfüllte das Haus', 'Engel erschienen ihnen'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Apostelgeschichte 2,3 – Es erschienen ihnen Zungen wie von Feuer, die sich verteilten und auf jeden Einzelnen setzten – sichtbares Zeichen der Geistausgiessung.',
      },
      {
        id: 'ap-q2',
        text: 'Was antwortete Petrus dem Rat, als dieser ihm verbot, im Namen Jesu zu predigen?',
        answers: ['"Wir müssen Gott mehr gehorchen als den Menschen."', '"Ihr könnt uns nicht aufhalten."', '"Wir tun, was Jesus uns befohlen hat."', '"Der Geist leitet uns."'],
        correct: 0,
        timeLimit: 20,
        explanation: 'Apostelgeschichte 5,29 – "Man muss Gott mehr gehorchen als den Menschen" – einer der mutigsten Sätze der frühen Kirche.',
      },
      {
        id: 'ap-q3',
        text: 'Was sah Stephanus kurz vor seinem Tod als er zu Himmel blickte?',
        answers: ['Einen Engel mit einem Schwert', 'Den Heiligen Geist als Taube', 'Jesus, der zur Rechten Gottes steht', 'Ein offenes Buch mit Namen'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Apostelgeschichte 7,56 – "Ich sehe den Himmel offen und den Menschensohn zur Rechten Gottes stehen." Interessanterweise steht Jesus hier – bei allen anderen Stellen sitzt er.',
      },
      {
        id: 'ap-q4',
        text: 'Wer war der äthiopische Kämmerer, dem Philippus das Evangelium erklärte?',
        answers: ['Ein General der äthiopischen Armee', 'Ein hoher Hofbeamter der Königin Kandake', 'Ein Händler aus Äthiopien', 'Ein jüdischer Pilger aus Äthiopien'],
        correct: 1,
        timeLimit: 25,
        explanation: 'Apostelgeschichte 8,27 – Er war Kämmerer (Schatzmeister) der Kandake, der Königin der Äthiopier, und hatte Jerusalem besucht. Er las aus Jesaja 53.',
      },
      {
        id: 'ap-q5',
        text: 'Welche Frau in Philippi öffnete Gott das Herz, sodass sie die erste Bekehrte in Europa wurde?',
        answers: ['Priszilla', 'Lydia', 'Phoebe', 'Tabitha'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Apostelgeschichte 16,14 – Lydia, eine Purpurhändlerin aus Thyatira, war die erste Bekehrte in Europa. Der HERR öffnete ihr Herz, dem zu folgen, was Paulus sagte.',
      },
      {
        id: 'ap-q6',
        text: 'Welches Argument verwendete Paulus in Athen auf dem Areopag, um die Griechen für den Gott der Bibel zu gewinnen?',
        answers: ['Er zitierte die Hebräische Schrift', 'Er verwies auf ihr Denkmal "Dem unbekannten Gott"', 'Er zeigte ihnen Wunder', 'Er kritisierte ihre Götter'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Apostelgeschichte 17,23 – "Ich fand auch einen Altar mit der Aufschrift: Dem unbekannten Gott. Was ihr nun unwissend verehrt, das verkündige ich euch." Paulus traf ihre Sprache.',
      },
      {
        id: 'ap-q7',
        text: 'Wie rechtfertigte Paulus sein Einspruchsrecht und die Reise nach Rom?',
        answers: ['Er war römischer Bürger und legte Berufung beim Kaiser ein', 'Er hatte einen Geleitbrief des Hohenpriesters', 'Er hatte Zeugen für seine Unschuld', 'Er wurde von einem Engel dazu aufgefordert'],
        correct: 0,
        timeLimit: 20,
        explanation: 'Apostelgeschichte 25,11 – "Ich berufe mich auf den Kaiser!" Als römischer Bürger hatte Paulus das Recht, seinen Fall vor den Kaiser zu bringen – und so kam er nach Rom.',
      },
    ],
  },

  // ─── 10. Bibel-Allgemeinwissen ───────────────────────────────────────────
  {
    id: 'default-gemischt-1',
    title: 'Bibel-Allgemeinwissen',
    category: 'Gemischt',
    description: 'Fragen quer durch die ganze Bibel für Fortgeschrittene',
    createdAt: 1700000009000,
    updatedAt: 1700000009000,
    questions: [
      {
        id: 'gm-q1',
        text: 'Welcher Vers der Bibel wird am häufigsten als "das Evangelium im Kleinen" bezeichnet?',
        answers: ['Römer 8,28', 'Johannes 3,16', 'Psalm 23,1', 'Matthäus 28,19'],
        correct: 1,
        timeLimit: 15,
        explanation: 'Johannes 3,16 – "Denn so hat Gott die Welt geliebt, dass er seinen eingeborenen Sohn gab..." fasst die ganze Heilsbotschaft in einem Vers zusammen.',
      },
      {
        id: 'gm-q2',
        text: 'Wer schrieb nach eigener Angabe die meisten Bücher des Neuen Testaments?',
        answers: ['Johannes', 'Lukas', 'Paulus', 'Matthäus'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Paulus schrieb 13 (oder 14 mit Hebräer) der 27 neutestamentlichen Bücher. Lukas schrieb mit dem Lukas-Evangelium und der Apostelgeschichte die meisten Wörter.',
      },
      {
        id: 'gm-q3',
        text: 'Wie heisst der kürzeste Vers der Bibel?',
        answers: ['"Betet ohne Unterlass." (1. Thess 5,17)', '"Jesus weinte." (Joh 11,35)', '"Rejoice." (Phil 4,4)', '"Amen." (Off 22,21)'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Johannes 11,35 – "Jesus weinte." (griechisch: "ἐδάκρυσεν ὁ Ἰησοῦς") – Der kürzeste Vers der Bibel zeigt Jesu Menschlichkeit und Mitgefühl.',
      },
      {
        id: 'gm-q4',
        text: 'Was bedeutet der Name "Immanuel", den Jesaja für den kommenden Messias ankündigte?',
        answers: ['"Gott rettet"', '"Gott ist mit uns"', '"Gott ist König"', '"Gott ist Licht"'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Jesaja 7,14 / Matthäus 1,23 – "Immanuel" (hebräisch: עִמָּנוּאֵל) bedeutet "Gott mit uns". Matthäus sieht diese Prophezeiung in Jesus erfüllt.',
      },
      {
        id: 'gm-q5',
        text: 'Welches Buch der Bibel nennt Gott nie beim Namen?',
        answers: ['Esther', 'Rut', 'Prediger', 'Hohelied'],
        correct: 0,
        timeLimit: 25,
        explanation: 'Das Buch Esther ist das einzige Buch der Bibel, in dem der Name Gottes überhaupt nicht vorkommt – und doch zeigt die Geschichte Gottes verborgene Führung.',
      },
      {
        id: 'gm-q6',
        text: 'Was ist der Unterschied zwischen den synoptischen Evangelien und dem Johannesevangelium?',
        answers: ['Johannes ist kürzer', 'Matthäus, Markus und Lukas haben viele Gemeinsamkeiten; Johannes ist eigenständig mit langen Reden', 'Johannes enthält nur Wunder', 'Die synoptischen Evangelien beginnen alle mit der Geburt Jesu'],
        correct: 1,
        timeLimit: 25,
        explanation: '"Synoptisch" (griech. = mit gleichen Augen sehend) – Matthäus, Markus und Lukas teilen viel Material. Johannes hat einen eigenen theologischen Schwerpunkt: die Gottheit Jesu.',
      },
      {
        id: 'gm-q7',
        text: 'Auf welchem Berg verklärte sich Jesus vor Petrus, Jakobus und Johannes?',
        answers: ['Ölberg', 'Berg Karmel', 'Einem hohen Berg – traditionell Berg Tabor', 'Berg Sinai'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Matthäus 17,1 – Die Bibel nennt nur "einen hohen Berg". Seit dem 4. Jahrhundert wird traditionell der Berg Tabor als Ort der Verklärung verehrt.',
      },
    ],
  },

  // ─── 11. Frauen der Bibel ────────────────────────────────────────────────
  {
    id: 'default-frauen-1',
    title: 'Frauen der Bibel',
    category: 'Gemischt',
    description: 'Mutige und bedeutsame Frauen aus dem Alten und Neuen Testament',
    createdAt: 1700000010000,
    updatedAt: 1700000010000,
    questions: [
      {
        id: 'fr-q1',
        text: 'Welche Frau rettete das Volk Israel, indem sie den feindlichen General Sisera tötete?',
        answers: ['Debora', 'Jael', 'Mirjam', 'Abigajil'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Richter 4,21 – Jael lockte den fliehenden General Sisera in ihr Zelt und schlug ihm einen Zeltpflock durch die Schläfe. Debora hatte prophezeit, dass der Sieg durch eine Frau kommen würde.',
      },
      {
        id: 'fr-q2',
        text: 'Was antwortete Rut ihrer Schwiegermutter Naomi, als diese sie nach Moab zurückschicken wollte?',
        answers: ['"Ich gehe mit dir, wohin du gehst."', '"Ich kann dich nicht verlassen."', '"Dein Gott ist mein Gott."', '"Beide Antworten A und C"'],
        correct: 3,
        timeLimit: 20,
        explanation: 'Rut 1,16 – "Wo du hingehst, will ich hingehen. Wo du stirbst, will ich sterben... Dein Gott ist mein Gott." Diese Treue gilt als eines der schönsten Treueversprechen der Bibel.',
      },
      {
        id: 'fr-q3',
        text: 'Wer war Esther, bevor sie Königin von Persien wurde?',
        answers: ['Eine jüdische Sklavin', 'Eine Tochter eines Beamten', 'Eine jüdische Waise, aufgezogen von ihrem Cousin Mordechai', 'Eine Priesterstochter'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Esther 2,7 – Esther war eine Waise, deren hebräischer Name Hadassa war. Ihr Cousin Mordechai hatte sie aufgezogen wie seine eigene Tochter.',
      },
      {
        id: 'fr-q4',
        text: 'Was tat Maria von Bethanien kurz vor Jesu Tod, das er für bedeutsam hielt?',
        answers: ['Sie wusch seine Füsse mit ihren Tränen', 'Sie salbte ihn mit kostbarem Nardenöl', 'Sie bereitete das Abendmahl vor', 'Sie betete laut für ihn'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Johannes 12,3 – Maria salbte Jesu Füsse mit einem Pfund echten, teuren Nardenöls. Jesus sagte: "Wo dieses Evangelium gepredigt wird, wird man auch von ihr reden."',
      },
      {
        id: 'fr-q5',
        text: 'Welche Frau führte die Prophetin Debora nach dem Sieg Israels die Frauen im Loblied an?',
        answers: ['Mirjam', 'Debora selbst', 'Hanna', 'Rut'],
        correct: 0,
        timeLimit: 25,
        explanation: '2. Mose 15,20 – Mirjam, die Schwester des Mose, nahm eine Handpauke und führte alle Frauen tanzend und singend an, nachdem das Heer Pharaos im Meer versunken war.',
      },
      {
        id: 'fr-q6',
        text: 'Was bat die Mutter der Söhne Zebedäus Jesus für ihre Kinder?',
        answers: ['Dass sie ihn begleiten dürften', 'Dass einer zu seiner Rechten und einer zu seiner Linken sitzen dürfe', 'Dass sie grosse Wunder tun dürften', 'Dass sie nicht sterben müssten'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Matthäus 20,21 – Sie bat: "Befiehl, dass diese meine zwei Söhne in deinem Reich sitzen, einer zu deiner Rechten und einer zu deiner Linken." Jesus antwortete mit einer Frage über den Kelch des Leidens.',
      },
      {
        id: 'fr-q7',
        text: 'Priszilla und Aquila unterrichteten einen eloquenten Mann aus Alexandria genauer im Glauben. Wie hiess er?',
        answers: ['Apollos', 'Titus', 'Timotheus', 'Barnabas'],
        correct: 0,
        timeLimit: 20,
        explanation: 'Apostelgeschichte 18,26 – Apollos war gebildet, kannte aber nur die Taufe des Johannes. Priszilla und Aquila nahmen ihn beiseite und erklärten ihm den Weg Gottes genauer.',
      },
    ],
  },

  // ─── 12. Die Bergpredigt ─────────────────────────────────────────────────
  {
    id: 'default-bergpredigt-1',
    title: 'Die Bergpredigt',
    category: 'Evangelien',
    description: 'Das Herzstück von Jesu Lehre aus Matthäus 5–7',
    createdAt: 1700000011000,
    updatedAt: 1700000011000,
    questions: [
      {
        id: 'bp-q1',
        text: 'Was verheisst die erste Seligpreisung: "Selig sind die Armen im Geist"?',
        answers: ['Sie werden Trost empfangen', 'Sie werden das Reich der Himmel besitzen', 'Sie werden die Erde erben', 'Sie werden Gott sehen'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Matthäus 5,3 – "Selig sind die Armen im Geist, denn ihrer ist das Reich der Himmel." Die "Armen im Geist" sind die, die ihre völlige Abhängigkeit von Gott erkennen.',
      },
      {
        id: 'bp-q2',
        text: 'Was soll man tun, wenn einem jemand auf die rechte Wange schlägt?',
        answers: ['Sich verteidigen', 'Wegzugehen', 'Auch die linke hinhalten', 'Den Richter anrufen'],
        correct: 2,
        timeLimit: 15,
        explanation: 'Matthäus 5,39 – "Wenn dich jemand auf die rechte Wange schlägt, dem biete auch die andere dar." Jesus lehrt, Gewalt nicht mit Gewalt zu beantworten.',
      },
      {
        id: 'bp-q3',
        text: 'Wie viele Bitten enthält das "Vaterunser" in der Bergpredigt (Matthäus 6)?',
        answers: ['5', '6', '7', '8'],
        correct: 2,
        timeLimit: 25,
        explanation: 'Das Vaterunser in Matthäus 6,9-13 enthält sieben Bitten: Drei betreffen Gottes Ehre (Name, Reich, Wille), vier betreffen menschliche Bedürfnisse (Brot, Vergebung, Versuchung, Erlösung).',
      },
      {
        id: 'bp-q4',
        text: 'Was sagt Jesus über das Schätzesammeln auf der Erde?',
        answers: ['Es ist erlaubt, wenn man Gott nicht vergisst', '"Sammelt nicht Schätze auf Erden, wo Motten und Rost sie fressen."', '"Gebt alles weg."', '"Teilt eure Schätze mit den Armen."'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Matthäus 6,19-20 – Jesus ruft auf, Schätze im Himmel zu sammeln, "wo weder Motte noch Rost frisst und wo keine Diebe einbrechen und stehlen."',
      },
      {
        id: 'bp-q5',
        text: 'Was ist die "goldene Regel" in der Bergpredigt?',
        answers: ['"Liebe deinen Nächsten wie dich selbst."', '"Alles, was ihr wollt, dass euch die Menschen tun sollen, das tut ihnen auch."', '"Tue niemandem, was du nicht willst, dass man dir tue."', '"Liebe Gott und deinen Nächsten."'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Matthäus 7,12 – "Alles nun, was ihr wollt, dass euch die Menschen tun sollen, das tut ihnen auch; denn das ist das Gesetz und die Propheten."',
      },
      {
        id: 'bp-q6',
        text: 'Womit vergleicht Jesus die, die sein Wort hören und danach tun?',
        answers: ['Mit einem Baum am Wasser', 'Mit einem Haus auf einem Felsen', 'Mit einem Licht auf dem Leuchter', 'Mit Salz in der Erde'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Matthäus 7,24 – "Jeden, der diese meine Worte hört und sie tut, den werde ich einem klugen Mann vergleichen, der sein Haus auf den Felsen baute."',
      },
      {
        id: 'bp-q7',
        text: 'Was sagt Jesus über das Beten in der Bergpredigt – wo soll man beten?',
        answers: ['In der Synagoge mit der Gemeinde', 'In deiner Kammer, in der Stille', 'Überall, zu jeder Zeit', 'Im Tempel am Altar'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Matthäus 6,6 – "Wenn du aber betest, so geh in dein Kämmerlein und schliess die Tür zu und bete zu deinem Vater im Verborgenen."',
      },
    ],
  },

  // ─── 13. Jesus – Letzte Woche ────────────────────────────────────────────
  {
    id: 'default-karwoche-1',
    title: 'Karwoche – Jesu letzte Tage',
    category: 'Evangelien',
    description: 'Von Palmsonntag bis zur Auferstehung',
    createdAt: 1700000012000,
    updatedAt: 1700000012000,
    questions: [
      {
        id: 'kw-q1',
        text: 'Auf welchem Tier ritt Jesus beim Einzug in Jerusalem?',
        answers: ['Auf einem Pferd', 'Auf einem Kamel', 'Auf einem Esel', 'Er ging zu Fuss'],
        correct: 2,
        timeLimit: 15,
        explanation: 'Matthäus 21,5 – Sacharja 9,9 hatte prophezeit: "Dein König kommt zu dir, demütig und auf einem Esel reitend." Jesus erfüllte diese Prophezeiung bewusst.',
      },
      {
        id: 'kw-q2',
        text: 'Was trieb Jesus am Dienstag der letzten Woche aus dem Tempel?',
        answers: ['Pharisäer und Schriftgelehrte', 'Geldwechsler und Taubenhändler', 'Heidnische Pilger', 'Römische Soldaten'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Matthäus 21,12 – Jesus warf die Tische der Geldwechsler um: "Mein Haus wird ein Bethaus genannt werden, ihr aber macht daraus eine Räuberhöhle."',
      },
      {
        id: 'kw-q3',
        text: 'Was symbolisierten Brot und Wein beim letzten Abendmahl laut Jesu eigenen Worten?',
        answers: ['Die Schöpfung Gottes', 'Seinen Leib und sein Blut des neuen Bundes', 'Das Passahlamm und den Wein der Freude', 'Das tägliche Brot und den Trost Gottes'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Matthäus 26,26-28 – "Das ist mein Leib... das ist mein Blut des neuen Bundes, das für viele vergossen wird zur Vergebung der Sünden."',
      },
      {
        id: 'kw-q4',
        text: 'Was betete Jesus in Getsemane kurz vor seiner Verhaftung?',
        answers: ['"Vater, vergib ihnen!"', '"Nicht wie ich will, sondern wie du willst."', '"Vater, in deine Hände befehle ich meinen Geist."', '"Es ist vollbracht!"'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Matthäus 26,39 – "Mein Vater, wenn es möglich ist, so gehe dieser Kelch an mir vorüber; doch nicht wie ich will, sondern wie du willst." Das Urbild christlicher Hingabe.',
      },
      {
        id: 'kw-q5',
        text: 'Welches der sieben letzten Worte Jesu am Kreuz richtete er an Gott?',
        answers: ['"Heute noch wirst du mit mir im Paradies sein."', '"Es ist vollbracht!"', '"Mein Gott, mein Gott, warum hast du mich verlassen?"', '"Vater, vergib ihnen!"'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Matthäus 27,46 – Dieses Wort entstammt Psalm 22 und beschreibt die tiefste Verlassenheit. Jesus trägt die Gottverlassenheit, die Sünde verursacht.',
      },
      {
        id: 'kw-q6',
        text: 'Wer half Jesus, das Kreuz zu tragen?',
        answers: ['Johannes der Jünger', 'Simon von Kyrene', 'Ein Soldat', 'Lazarus'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Markus 15,21 – Simon von Kyrene, Vater von Alexander und Rufus (bekannte Personen in der frühen Gemeinde), wurde gezwungen, das Kreuz Jesu zu tragen.',
      },
      {
        id: 'kw-q7',
        text: 'Was sagten die Engel zu den Frauen am leeren Grab?',
        answers: ['"Er ist auferstanden, wie er gesagt hat."', '"Geht schnell hin und sagt es seinen Jüngern."', '"Warum sucht ihr den Lebenden bei den Toten?"', '"Er ist nicht hier, er ist auferstanden."'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Lukas 24,5-6 – "Was sucht ihr den Lebenden bei den Toten? Er ist nicht hier, er ist auferstanden." Diese Frage der Engel ist eine der kraftvollsten der Bibel.',
      },
    ],
  },

  // ─── 14. Zahlen der Bibel ────────────────────────────────────────────────
  {
    id: 'default-zahlen-1',
    title: 'Zahlen & Fakten der Bibel',
    category: 'Gemischt',
    description: 'Bibelwissen mit Zahlen – Fakten und Rekorde',
    createdAt: 1700000013000,
    updatedAt: 1700000013000,
    questions: [
      {
        id: 'za-q1',
        text: 'Wie alt wurde Methusalem – der älteste Mensch der Bibel?',
        answers: ['777 Jahre', '900 Jahre', '969 Jahre', '999 Jahre'],
        correct: 2,
        timeLimit: 20,
        explanation: '1. Mose 5,27 – Methusalem wurde 969 Jahre alt und ist damit der älteste in der Bibel genannte Mensch. Sein Name bedeutet möglicherweise "Mann des Wurfspiesss" oder "Wenn er stirbt, kommt es."',
      },
      {
        id: 'za-q2',
        text: 'Wie viele Bücher hat das Neue Testament?',
        answers: ['24', '27', '30', '39'],
        correct: 1,
        timeLimit: 15,
        explanation: 'Das Neue Testament besteht aus 27 Büchern: 4 Evangelien, Apostelgeschichte, 21 Briefe und die Offenbarung.',
      },
      {
        id: 'za-q3',
        text: 'Wie viele Tage fastete Jesus in der Wüste?',
        answers: ['7 Tage', '20 Tage', '40 Tage', '50 Tage'],
        correct: 2,
        timeLimit: 15,
        explanation: 'Matthäus 4,2 – Jesus fastete vierzig Tage und vierzig Nächte, ehe ihn der Teufel versuchte. Die Zahl 40 ist in der Bibel oft mit Prüfung und Vorbereitung verbunden.',
      },
      {
        id: 'za-q4',
        text: 'Wie viele Frauen begleiteten Jesus und die zwölf Jünger auf ihren Reisen?',
        answers: ['Keine – Frauen folgten nicht', 'Eine – Maria Magdalena', 'Einige, darunter Maria Magdalena, Johanna und Susanna', 'Genau zwölf'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Lukas 8,1-3 – Mehrere Frauen begleiteten Jesus und versorgten ihn von ihrem Vermögen: Maria Magdalena, Johanna (Frau des Chusa), Susanna und viele andere.',
      },
      {
        id: 'za-q5',
        text: 'Wie viele Menschen kamen laut Apostelgeschichte am ersten Pfingstfest zum Glauben?',
        answers: ['300', '1.000', '3.000', '5.000'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Apostelgeschichte 2,41 – "So nahmen nun die, die sein Wort gern annahmen, die Taufe an; und es wurden an jenem Tag hinzugefügt etwa dreitausend Seelen."',
      },
      {
        id: 'za-q6',
        text: 'Wie lange war Jona im Bauch des grossen Fisches?',
        answers: ['Einen Tag', 'Zwei Tage', 'Drei Tage und drei Nächte', 'Sieben Tage'],
        correct: 2,
        timeLimit: 15,
        explanation: 'Jona 2,1 – "Jona war im Bauch des Fisches drei Tage und drei Nächte." Jesus bezog sich darauf als "Zeichen des Jona" für seine eigene Auferstehung (Matthäus 12,40).',
      },
      {
        id: 'za-q7',
        text: 'Wie viele Mal zogen die Israeliten um die Mauern Jerichos, bevor diese fielen?',
        answers: ['7 Mal am letzten Tag (13 Mal total)', '7 Mal total', '3 Mal', '1 Mal am letzten Tag'],
        correct: 0,
        timeLimit: 25,
        explanation: 'Josua 6,14-15 – Sechs Tage je einmal, am siebten Tag siebenmal – also 13 Mal insgesamt. Beim letzten Mal stiessen die Priester in die Hörner, das Volk schrie, und die Mauern fielen.',
      },
    ],
  },

  // ─── 15. Die Offenbarung ─────────────────────────────────────────────────
  {
    id: 'default-offenbarung-1',
    title: 'Die Offenbarung',
    category: 'NT',
    description: 'Das letzte Buch der Bibel – Bilder und Verheissungen',
    createdAt: 1700000014000,
    updatedAt: 1700000014000,
    questions: [
      {
        id: 'of-q1',
        text: 'An wen schrieb Johannes die Offenbarung?',
        answers: ['An die Gemeinden in Israel', 'An sieben Gemeinden in der Provinz Asia', 'An die Gemeinde in Rom', 'An alle Christen weltweit'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Offenbarung 1,11 – Johannes sollte schreiben, was er sah, und es an die sieben Gemeinden senden: Ephesus, Smyrna, Pergamon, Thyatira, Sardes, Philadelphia und Laodizea.',
      },
      {
        id: 'of-q2',
        text: 'Was symbolisieren die vier Lebewesen um den Thron Gottes in Offenbarung 4?',
        answers: ['Die vier Evangelisten', 'Löwe, Stier, Mensch und Adler', 'Die vier Erzengel', 'Die vier Weltreiche'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Offenbarung 4,7 – Die vier Lebewesen mit Löwe, Stier, Menschengesicht und Adler entsprechen den Cherubim bei Hesekiel und werden traditionell mit den vier Evangelisten verbunden.',
      },
      {
        id: 'of-q3',
        text: 'Was ist die Bedeutung der Zahl 144.000 in Offenbarung 7?',
        answers: ['Genau 144.000 Menschen werden gerettet', '12.000 aus jedem der zwölf Stämme Israels – Sinnbild für die vollständige Gemeinde Gottes', 'Die Anzahl der Märtyrer', 'Die Anzahl der Engel Gottes'],
        correct: 1,
        timeLimit: 25,
        explanation: 'Offenbarung 7,4 – Die meisten Ausleger sehen in 144.000 (12 × 12 × 1.000) eine symbolische Zahl für die vollständige, versiegelte Gemeinde – nicht eine buchstäbliche Zahl.',
      },
      {
        id: 'of-q4',
        text: 'Was verheisst Gott der Gemeinde in Laodizea, wenn sie aufmacht, wenn er anklopft?',
        answers: ['Eine Krone der Herrlichkeit', 'Er wird eintreten und mit ihr Mahl halten', 'Sie wird auf dem Thron sitzen', 'Sie wird weisse Kleider bekommen'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Offenbarung 3,20 – "Wer meine Stimme hört und die Tür aufmacht, zu dem werde ich hineingehen und das Abendmahl mit ihm halten, und er mit mir."',
      },
      {
        id: 'of-q5',
        text: 'Was ist das erste, was in der neuen Schöpfung nicht mehr sein wird, laut Offenbarung 21?',
        answers: ['Der Tod und die Sünde', 'Das Meer', 'Die Nacht', 'Der Tempel'],
        correct: 1,
        timeLimit: 25,
        explanation: 'Offenbarung 21,1 – "Und das Meer ist nicht mehr." Das Meer galt in der antiken Welt als Symbol des Chaos und der Bedrohung. In der neuen Schöpfung gibt es keine Unordnung mehr.',
      },
      {
        id: 'of-q6',
        text: 'Mit welchem Bild beschreibt die Offenbarung das ewige Leben in der neuen Stadt Jerusalem?',
        answers: ['Als Wolken im Himmel', 'Als Strom des Lebens und Baum des Lebens', 'Als Tempel aus Gold', 'Als Thron und Krone'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Offenbarung 22,1-2 – "Und er zeigte mir einen Strom des Lebens... und zu beiden Seiten des Stroms stand der Baum des Lebens." Eine Rückkehr zum Paradies aus 1. Mose.',
      },
      {
        id: 'of-q7',
        text: 'Mit welchen Worten endet die Bibel?',
        answers: ['"Friede sei mit allen, die in Christus sind."', '"Amen, ja, komm, Herr Jesus! Die Gnade des Herrn Jesus sei mit allen!"', '"Gelobt sei Gott in Ewigkeit."', '"Kommt, ihr Gesegneten meines Vaters."'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Offenbarung 22,20-21 – Die Bibel endet mit dem Gebet "Amen, ja, komm, Herr Jesus!" (Maranatha) und dem Segenwunsch – ein Aufruf zur Erwartung und Gnade.',
      },
    ],
  },
];
