import { QuizSet } from './quiz-types';

export const DEFAULT_QUIZ_SETS: QuizSet[] = [
  {
    id: 'default-at-1',
    title: 'Altes Testament Klassiker',
    category: 'AT',
    description: 'Bekannte Geschichten aus dem Alten Testament',
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
    questions: [
      {
        id: 'at-q1',
        text: 'Was war die erste Plage, die Gott über Ägypten schickte?',
        answers: ['Wasser wurde zu Blut', 'Frösche', 'Heuschrecken', 'Finsternis'],
        correct: 0,
        timeLimit: 20,
        explanation: '2. Mose 7,20 – Das Wasser des Nils wurde zu Blut.',
      },
      {
        id: 'at-q2',
        text: 'Wie viele Tage und Nächte regnete es während der Sintflut?',
        answers: ['20 Tage', '30 Tage', '40 Tage', '7 Tage'],
        correct: 2,
        timeLimit: 20,
        explanation: '1. Mose 7,4 – Es regnete 40 Tage und 40 Nächte.',
      },
      {
        id: 'at-q3',
        text: 'Womit erschlug David den Riesen Goliat?',
        answers: ['Mit einem Schwert', 'Mit einem Speer', 'Mit einem Stein und einer Schleuder', 'Mit einem Bogen'],
        correct: 2,
        timeLimit: 20,
        explanation: '1. Samuel 17,49 – David nahm einen Stein und schleuderte ihn.',
      },
      {
        id: 'at-q4',
        text: 'In welcher Stadt wurde der Tempel Salomos gebaut?',
        answers: ['Bethlehem', 'Nazareth', 'Jericho', 'Jerusalem'],
        correct: 3,
        timeLimit: 20,
        explanation: '1. Könige 6,1 – Salomo baute den Tempel in Jerusalem.',
      },
      {
        id: 'at-q5',
        text: 'Wer wurde in die Löwengrube geworfen, weil er trotz Verbot betete?',
        answers: ['Esra', 'Nehemia', 'Daniel', 'Hesekiel'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Daniel 6 – Daniel betete täglich und wurde in die Löwengrube geworfen.',
      },
      {
        id: 'at-q6',
        text: 'Wer war der erste Mensch, den Gott erschuf?',
        answers: ['Noah', 'Abraham', 'Adam', 'Mose'],
        correct: 2,
        timeLimit: 15,
        explanation: '1. Mose 2,7 – Gott formte Adam aus dem Staub des Erdbodens.',
      },
      {
        id: 'at-q7',
        text: 'Wie viele Jahre irrte Israel in der Wüste umher?',
        answers: ['20 Jahre', '30 Jahre', '40 Jahre', '50 Jahre'],
        correct: 2,
        timeLimit: 20,
        explanation: '4. Mose 14,33 – Israel wanderte 40 Jahre durch die Wüste.',
      },
      {
        id: 'at-q8',
        text: 'Wer rettete sein Volk, indem er die Mauern Jerichos zum Einsturz brachte?',
        answers: ['Mose', 'Josua', 'Kaleb', 'Samuel'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Josua 6 – Josua führte Israel um Jericho, und die Mauern fielen.',
      },
    ],
  },
  {
    id: 'default-nt-1',
    title: 'Neues Testament Grundlagen',
    category: 'NT',
    description: 'Wichtige Ereignisse und Lehren aus dem Neuen Testament',
    createdAt: 1700000001000,
    updatedAt: 1700000001000,
    questions: [
      {
        id: 'nt-q1',
        text: 'Wie viele Jünger berief Jesus in seinen engsten Kreis?',
        answers: ['10', '12', '7', '24'],
        correct: 1,
        timeLimit: 15,
        explanation: 'Matthäus 10,1 – Jesus berief seine zwölf Jünger.',
      },
      {
        id: 'nt-q2',
        text: 'Wer taufte Jesus im Jordan?',
        answers: ['Petrus', 'Andreas', 'Johannes der Täufer', 'Zacharias'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Matthäus 3,13-16 – Johannes der Täufer taufte Jesus im Jordan.',
      },
      {
        id: 'nt-q3',
        text: 'Welches Wunder vollbrachte Jesus bei der Hochzeit zu Kana?',
        answers: ['Er heilte einen Blinden', 'Er verwandelte Wasser in Wein', 'Er weckte einen Toten auf', 'Er stillte den Sturm'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Johannes 2,1-11 – Jesus verwandelte Wasser in Wein – sein erstes Wunder.',
      },
      {
        id: 'nt-q4',
        text: 'Was sagte Pontius Pilatus, nachdem er Jesus unschuldig befunden hatte?',
        answers: ['"Er ist schuldig!"', '"Ich wasche meine Hände in Unschuld."', '"Kreuzigt ihn sofort!"', '"Lasst ihn frei."'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Matthäus 27,24 – Pilatus wusch seine Hände als Zeichen seiner Unschuld.',
      },
      {
        id: 'nt-q5',
        text: 'An welchem Fest wurde der Heilige Geist auf die Jünger ausgegossen?',
        answers: ['Passah', 'Pfingsten', 'Laubhütten', 'Hannukka'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Apostelgeschichte 2,1 – Am Pfingstfest kam der Heilige Geist.',
      },
      {
        id: 'nt-q6',
        text: 'Wie hieß Paulus ursprünglich, bevor er Christ wurde?',
        answers: ['Simon', 'Saulus', 'Barnabas', 'Lukas'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Apostelgeschichte 9 – Saulus wurde nach seiner Bekehrung Paulus genannt.',
      },
      {
        id: 'nt-q7',
        text: 'Welches ist das kürzeste Evangelium?',
        answers: ['Matthäus', 'Lukas', 'Markus', 'Johannes'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Das Markusevangelium ist mit 16 Kapiteln das kürzeste der vier Evangelien.',
      },
      {
        id: 'nt-q8',
        text: 'In welcher Stadt wurde Paulus auf dem Weg nach Damaskus bekehrt?',
        answers: ['Auf dem Weg nach Damaskus', 'In Antiochia', 'In Korinth', 'In Jerusalem'],
        correct: 0,
        timeLimit: 20,
        explanation: 'Apostelgeschichte 9,3 – Paulus erlebte seine Bekehrung auf dem Weg nach Damaskus.',
      },
    ],
  },
  {
    id: 'default-evangelien-1',
    title: 'Gleichnisse Jesu',
    category: 'Evangelien',
    description: 'Die bekanntesten Gleichnisse aus den Evangelien',
    createdAt: 1700000002000,
    updatedAt: 1700000002000,
    questions: [
      {
        id: 'gl-q1',
        text: 'In welchem Gleichnis kehrt ein verlorener Sohn reumütig zu seinem Vater zurück?',
        answers: ['Gleichnis vom verlorenen Schaf', 'Gleichnis vom verlorenen Sohn', 'Gleichnis vom Sämann', 'Gleichnis von den Talenten'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Lukas 15,11-32 – Das Gleichnis vom verlorenen Sohn.',
      },
      {
        id: 'gl-q2',
        text: 'Im Gleichnis vom Sämann – was bedeutet der Samen, der auf den Weg fiel?',
        answers: ['Menschen, die das Wort hören und sofort vergessen', 'Menschen ohne Wurzeln', 'Menschen, die durch Sorgen abgelenkt werden', 'Menschen, die Frucht bringen'],
        correct: 0,
        timeLimit: 25,
        explanation: 'Matthäus 13,19 – Der Same auf dem Weg sind Menschen, die das Wort hören, aber nicht verstehen.',
      },
      {
        id: 'gl-q3',
        text: 'Wer half dem Mann, der auf dem Weg von Jerusalem nach Jericho überfallen wurde?',
        answers: ['Ein Priester', 'Ein Levit', 'Ein Samariter', 'Ein Pharisäer'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Lukas 10,33 – Ein Samariter half dem verletzten Mann – daher "Barmherziger Samariter".',
      },
      {
        id: 'gl-q4',
        text: 'Wie viele Talente bekam der Diener, der sie vergrub?',
        answers: ['5 Talente', '2 Talente', '1 Talent', '10 Talente'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Matthäus 25,18 – Der Diener, der 1 Talent bekam, vergrub es.',
      },
      {
        id: 'gl-q5',
        text: 'Welches Gleichnis beschreibt das Reich Gottes als ein Senfkorn?',
        answers: ['Das Gleichnis vom Senfkorn', 'Das Gleichnis vom Weinberg', 'Das Gleichnis vom Sauerteig', 'Das Gleichnis vom Fischnetz'],
        correct: 0,
        timeLimit: 20,
        explanation: 'Matthäus 13,31-32 – Das Senfkorn wächst zum größten Baum im Garten.',
      },
      {
        id: 'gl-q6',
        text: 'Im Gleichnis von den zehn Jungfrauen – wie viele hatten genug Öl?',
        answers: ['3', '5', '7', '10'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Matthäus 25,1-13 – Fünf kluge Jungfrauen hatten genug Öl für ihre Lampen.',
      },
      {
        id: 'gl-q7',
        text: 'Wer baute sein Haus auf Sand?',
        answers: ['Der törichte Mann', 'Der weise Mann', 'Der reiche Mann', 'Der arme Mann'],
        correct: 0,
        timeLimit: 15,
        explanation: 'Matthäus 7,26 – Der törichte Mann baute sein Haus auf Sand.',
      },
    ],
  },
  {
    id: 'default-psalmen-1',
    title: 'Psalmen & Weisheit',
    category: 'Psalmen',
    description: 'Fragen zu den Psalmen und Weisheitsbüchern',
    createdAt: 1700000003000,
    updatedAt: 1700000003000,
    questions: [
      {
        id: 'ps-q1',
        text: 'Wie beginnt Psalm 23?',
        answers: ['"Gott ist unsere Zuflucht"', '"Der HERR ist mein Hirte"', '"Ich hebe meine Augen auf"', '"Lobt den HERRN alle Völker"'],
        correct: 1,
        timeLimit: 15,
        explanation: 'Psalm 23,1 – "Der HERR ist mein Hirte, mir wird nichts mangeln."',
      },
      {
        id: 'ps-q2',
        text: 'Wer hat die meisten Psalmen geschrieben?',
        answers: ['Mose', 'Salomo', 'David', 'Asaf'],
        correct: 2,
        timeLimit: 20,
        explanation: '73 Psalmen tragen die Überschrift "Von David".',
      },
      {
        id: 'ps-q3',
        text: 'Wie viele Psalmen gibt es insgesamt im Buch der Psalmen?',
        answers: ['100', '120', '150', '180'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Das Buch der Psalmen enthält 150 Psalmen.',
      },
      {
        id: 'ps-q4',
        text: 'Was sagt Sprüche 3,5 über das Vertrauen?',
        answers: ['"Vertrau auf deine eigene Kraft"', '"Vertrau auf den HERRN von ganzem Herzen"', '"Vertrau keinem Menschen"', '"Vertrau auf deine Weisheit"'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Sprüche 3,5 – "Vertrau auf den HERRN von ganzem Herzen."',
      },
      {
        id: 'ps-q5',
        text: 'Welcher Psalm beginnt mit "Wie der Hirsch lechzt nach Wasserquellen"?',
        answers: ['Psalm 1', 'Psalm 22', 'Psalm 42', 'Psalm 100'],
        correct: 2,
        timeLimit: 25,
        explanation: 'Psalm 42,1 – "Wie der Hirsch lechzt nach frischem Wasser, so lechzt meine Seele nach dir, o Gott."',
      },
      {
        id: 'ps-q6',
        text: 'Was sagt Psalm 119,105 über Gottes Wort?',
        answers: ['"Es ist Kraft für mein Herz"', '"Es ist meines Fußes Leuchte"', '"Es ist mein tägliches Brot"', '"Es ist mein Schwert"'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Psalm 119,105 – "Dein Wort ist meines Fußes Leuchte und ein Licht auf meinem Weg."',
      },
      {
        id: 'ps-q7',
        text: 'Welches Buch enthält den berühmten Satz: "Alles hat seine Zeit"?',
        answers: ['Psalmen', 'Sprüche', 'Hiob', 'Prediger'],
        correct: 3,
        timeLimit: 20,
        explanation: 'Prediger 3,1 – "Alles hat seine Zeit, und jedes Vorhaben unter dem Himmel hat seine Stunde."',
      },
    ],
  },
  {
    id: 'default-propheten-1',
    title: 'Die Propheten',
    category: 'Propheten',
    description: 'Fragen zu den Propheten des Alten Testaments',
    createdAt: 1700000004000,
    updatedAt: 1700000004000,
    questions: [
      {
        id: 'pr-q1',
        text: 'Welcher Prophet wurde von einem großen Fisch verschluckt?',
        answers: ['Elia', 'Elisa', 'Jona', 'Amos'],
        correct: 2,
        timeLimit: 15,
        explanation: 'Jona 1,17 – Jona wurde drei Tage und drei Nächte im Bauch des Fisches gehalten.',
      },
      {
        id: 'pr-q2',
        text: 'Welcher Prophet sagte voraus: "Eine Jungfrau wird schwanger werden und einen Sohn gebären"?',
        answers: ['Jeremia', 'Hesekiel', 'Jesaja', 'Micha'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Jesaja 7,14 – Die Prophezeiung von der Jungfrau, die Immanuel gebären wird.',
      },
      {
        id: 'pr-q3',
        text: 'Welcher Prophet wurde lebend in den Himmel aufgenommen (in einem feurigen Wagen)?',
        answers: ['Elisa', 'Elia', 'Enoch', 'Mose'],
        correct: 1,
        timeLimit: 20,
        explanation: '2. Könige 2,11 – Elia fuhr im Sturmwind zum Himmel auf, begleitet von einem feurigen Wagen.',
      },
      {
        id: 'pr-q4',
        text: 'Aus welcher Stadt stammte der Prophet Micha?',
        answers: ['Jerusalem', 'Bethlehem', 'Moreseth', 'Anathoth'],
        correct: 2,
        timeLimit: 25,
        explanation: 'Micha 1,1 – Micha stammte aus Moreseth.',
      },
      {
        id: 'pr-q5',
        text: 'Welcher Prophet sah eine Vision von verdorrten Knochen, die wieder lebendig wurden?',
        answers: ['Jesaja', 'Jeremia', 'Daniel', 'Hesekiel'],
        correct: 3,
        timeLimit: 20,
        explanation: 'Hesekiel 37 – Die Vision vom Tal der verdorrten Knochen, die durch Gottes Geist lebendig werden.',
      },
      {
        id: 'pr-q6',
        text: 'Welcher Prophet predigte in Ninive Buße?',
        answers: ['Jona', 'Nahum', 'Zephanja', 'Habakuk'],
        correct: 0,
        timeLimit: 20,
        explanation: 'Jona 3 – Jona rief die Stadt Ninive zur Umkehr auf, und sie fasteten.',
      },
      {
        id: 'pr-q7',
        text: 'Wie viele sogenannte "große Propheten" gibt es im Alten Testament?',
        answers: ['3', '4', '5', '6'],
        correct: 2,
        timeLimit: 25,
        explanation: 'Es gibt 5 große Propheten: Jesaja, Jeremia, Klagelieder, Hesekiel und Daniel.',
      },
    ],
  },
  {
    id: 'default-paulus-1',
    title: 'Paulus & seine Briefe',
    category: 'Paulus',
    description: 'Fragen zu den Paulusbriefen und seiner Missionsreise',
    createdAt: 1700000005000,
    updatedAt: 1700000005000,
    questions: [
      {
        id: 'pau-q1',
        text: 'An welche Gemeinde schrieb Paulus: "Ich vermag alles durch den, der mich stärkt"?',
        answers: ['Die Römer', 'Die Korinther', 'Die Philipper', 'Die Galater'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Philipper 4,13 – Dieser bekannte Vers stammt aus dem Philipperbrief.',
      },
      {
        id: 'pau-q2',
        text: 'Welcher Brief des Paulus handelt hauptsächlich von der Rechtfertigung durch Glauben?',
        answers: ['1. Korinther', 'Römer', 'Galater', 'Epheser'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Der Römerbrief ist Paulus\' ausführlichste Darlegung der Rechtfertigung durch Glauben.',
      },
      {
        id: 'pau-q3',
        text: 'In welchem Brief schreibt Paulus das berühmte "Hohelied der Liebe" (1. Kor 13)?',
        answers: ['Römer', '1. Korinther', 'Epheser', '1. Timotheus'],
        correct: 1,
        timeLimit: 20,
        explanation: '1. Korinther 13 – "Die Liebe ist langmütig und freundlich..."',
      },
      {
        id: 'pau-q4',
        text: 'Wie viele Missionsreisen unternahm Paulus insgesamt?',
        answers: ['2', '3', '4', '5'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Paulus unternahm drei große Missionsreisen, die in der Apostelgeschichte beschrieben sind.',
      },
      {
        id: 'pau-q5',
        text: 'Wo war Paulus, als er den Philipperbrief schrieb?',
        answers: ['In Korinth', 'Auf einer Schiffsreise', 'Im Gefängnis', 'In Antiochia'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Paulus schrieb den Philipperbrief aus dem Gefängnis – daher wird er "Gefängnisbrief" genannt.',
      },
      {
        id: 'pau-q6',
        text: 'An wen schrieb Paulus den Brief, in dem er um die Freilassung des Sklaven Onesimus bat?',
        answers: ['Timotheus', 'Titus', 'Philemon', 'Apollos'],
        correct: 2,
        timeLimit: 25,
        explanation: 'Der Brief an Philemon handelt vom Sklaven Onesimus.',
      },
      {
        id: 'pau-q7',
        text: 'Welches sind die "Früchte des Geistes" laut Paulus in Galater 5?',
        answers: ['Glaube, Hoffnung, Liebe', 'Liebe, Freude, Friede...', 'Weisheit, Kraft, Reichtum', 'Demut, Geduld, Stärke'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Galater 5,22 – "Die Frucht des Geistes ist Liebe, Freude, Friede, Langmut..."',
      },
    ],
  },
  {
    id: 'default-wunder-1',
    title: 'Wunder Jesu',
    category: 'Evangelien',
    description: 'Die grossen Wunder und Zeichen Jesu',
    createdAt: 1700000006000,
    updatedAt: 1700000006000,
    questions: [
      {
        id: 'wu-q1',
        text: 'Wie viele Menschen speiste Jesus mit fünf Broten und zwei Fischen?',
        answers: ['1.000 Männer', '3.000 Menschen', '5.000 Männer', '10.000 Menschen'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Matthäus 14,21 – Es aßen etwa 5.000 Männer, ohne Frauen und Kinder.',
      },
      {
        id: 'wu-q2',
        text: 'Wen erweckte Jesus in Bethanien von den Toten?',
        answers: ['Jairus', 'Lazarus', 'Stephanus', 'Zachäus'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Johannes 11 – Jesus erweckte Lazarus, den Bruder von Maria und Marta.',
      },
      {
        id: 'wu-q3',
        text: 'Auf welchem See lief Jesus übers Wasser?',
        answers: ['Totes Meer', 'See Genezareth', 'Mittelmeer', 'Jordanfluss'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Matthäus 14,25 – Jesus ging auf dem See Genezareth (auch See von Tiberias) übers Wasser.',
      },
      {
        id: 'wu-q4',
        text: 'Wie lange war der Mann am Teich Betesda krank, den Jesus heilte?',
        answers: ['10 Jahre', '20 Jahre', '38 Jahre', '40 Jahre'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Johannes 5,5 – Der Mann war 38 Jahre lang krank.',
      },
      {
        id: 'wu-q5',
        text: 'Was heilte Jesus am Gehörten aus Dekapolis?',
        answers: ['Er war blind', 'Er war gelähmt', 'Er war taubstumm', 'Er hatte Aussatz'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Markus 7,32 – Jesus heilte einen Taubstummen mit den Worten "Effata" (Tu dich auf).',
      },
      {
        id: 'wu-q6',
        text: 'Was sagte Jesus zum Sturm auf dem See?',
        answers: ['"Geh weg!"', '"Schweig, sei still!"', '"Hör auf!"', '"Im Namen Gottes!"'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Markus 4,39 – Jesus sprach zum Sturm: "Schweig, sei still!" und es wurde windstill.',
      },
      {
        id: 'wu-q7',
        text: 'Welches war das erste Wunder Jesu?',
        answers: ['Er heilte einen Aussätzigen', 'Er verwandelte Wasser in Wein', 'Er trieb böse Geister aus', 'Er erweckte einen Toten'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Johannes 2,11 – Die Verwandlung von Wasser in Wein bei der Hochzeit zu Kana war Jesu erstes Zeichen.',
      },
    ],
  },
  {
    id: 'default-schoepfung-1',
    title: 'Schöpfung & Anfänge',
    category: 'AT',
    description: 'Die ersten Bücher der Bibel – von der Schöpfung bis zu den Erzvätern',
    createdAt: 1700000007000,
    updatedAt: 1700000007000,
    questions: [
      {
        id: 'sc-q1',
        text: 'Was erschuf Gott am ersten Tag?',
        answers: ['Die Erde und das Meer', 'Licht', 'Pflanzen', 'Die Sonne'],
        correct: 1,
        timeLimit: 15,
        explanation: '1. Mose 1,3 – Am ersten Tag sprach Gott: "Es werde Licht!"',
      },
      {
        id: 'sc-q2',
        text: 'Aus was wurde Eva erschaffen?',
        answers: ['Aus Lehm', 'Aus Adams Rippe', 'Aus Staub', 'Aus Wasser'],
        correct: 1,
        timeLimit: 15,
        explanation: '1. Mose 2,22 – Gott formte Eva aus einer Rippe Adams.',
      },
      {
        id: 'sc-q3',
        text: 'Welches Zeichen gab Gott als Versprechen, die Erde nie wieder mit einer Flut zu vernichten?',
        answers: ['Eine Taube', 'Ein Regenbogen', 'Ein Stern', 'Ein Olivenbaum'],
        correct: 1,
        timeLimit: 20,
        explanation: '1. Mose 9,13 – Gott setzte seinen Bogen in die Wolken als Zeichen des Bundes.',
      },
      {
        id: 'sc-q4',
        text: 'Wie hieß die Stadt, deren Turm die Menschen bis in den Himmel bauen wollten?',
        answers: ['Ninive', 'Ur', 'Babel', 'Sodom'],
        correct: 2,
        timeLimit: 20,
        explanation: '1. Mose 11,1-9 – Der Turmbau zu Babel führte zur Sprachverwirrung.',
      },
      {
        id: 'sc-q5',
        text: 'Was versprach Gott Abraham bezüglich seiner Nachkommen?',
        answers: ['Reichtum und Macht', 'So zahlreich wie Sterne am Himmel', '12 Söhne', 'Ein langes Leben'],
        correct: 1,
        timeLimit: 20,
        explanation: '1. Mose 15,5 – Gott versprach Abraham Nachkommen, so zahlreich wie die Sterne.',
      },
      {
        id: 'sc-q6',
        text: 'Wer war der Lieblingssohn Jakobs, dem er ein buntes Kleid schenkte?',
        answers: ['Ruben', 'Juda', 'Josef', 'Benjamin'],
        correct: 2,
        timeLimit: 20,
        explanation: '1. Mose 37,3 – Jakob liebte Josef mehr als alle anderen Söhne und gab ihm ein Kleid mit langen Ärmeln.',
      },
      {
        id: 'sc-q7',
        text: 'Wozu war Josef in Ägypten aufgestiegen?',
        answers: ['Zum Priester', 'Zum Heerführer', 'Zum Statthalter', 'Zum Kaufmann'],
        correct: 2,
        timeLimit: 20,
        explanation: '1. Mose 41,41 – Pharao setzte Josef als Statthalter über ganz Ägypten ein.',
      },
    ],
  },
  {
    id: 'default-apostel-1',
    title: 'Apostelgeschichte',
    category: 'NT',
    description: 'Die Ausbreitung der frühen Kirche',
    createdAt: 1700000008000,
    updatedAt: 1700000008000,
    questions: [
      {
        id: 'ap-q1',
        text: 'Wer predigte am ersten Pfingstfest und gewann 3.000 Bekehrte?',
        answers: ['Johannes', 'Paulus', 'Petrus', 'Stephanus'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Apostelgeschichte 2,14.41 – Petrus hielt die Pfingstpredigt, nach der 3.000 Menschen glaubten.',
      },
      {
        id: 'ap-q2',
        text: 'Wer war der erste christliche Märtyrer?',
        answers: ['Jakobus', 'Barnabas', 'Stephanus', 'Philippus'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Apostelgeschichte 7 – Stephanus wurde gesteinigt und war damit der erste christliche Märtyrer.',
      },
      {
        id: 'ap-q3',
        text: 'In welcher Stadt wurden die Jünger erstmals "Christen" genannt?',
        answers: ['Jerusalem', 'Antiochia', 'Korinth', 'Rom'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Apostelgeschichte 11,26 – In Antiochia wurden die Jünger zuerst "Christen" genannt.',
      },
      {
        id: 'ap-q4',
        text: 'Wer begleitete Paulus auf seiner ersten Missionsreise?',
        answers: ['Silas', 'Timotheus', 'Barnabas', 'Lukas'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Apostelgeschichte 13,2 – Barnabas und Paulus wurden für die erste Missionsreise ausgesandt.',
      },
      {
        id: 'ap-q5',
        text: 'Wo saßen Paulus und Silas im Gefängnis und sangen Loblieder?',
        answers: ['In Korinth', 'In Philippi', 'In Thessalonich', 'In Athen'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Apostelgeschichte 16,25 – In Philippi beteten Paulus und Silas und sangen Loblieder Gott.',
      },
      {
        id: 'ap-q6',
        text: 'Auf welcher Insel erlitt Paulus Schiffbruch auf dem Weg nach Rom?',
        answers: ['Kreta', 'Zypern', 'Malta', 'Korfu'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Apostelgeschichte 28,1 – Nach dem Schiffbruch kamen sie auf die Insel Malta.',
      },
      {
        id: 'ap-q7',
        text: 'Wer schlief während einer langen Predigt des Paulus ein und fiel aus dem Fenster?',
        answers: ['Timotheus', 'Eutychus', 'Tychikus', 'Aristarchus'],
        correct: 1,
        timeLimit: 25,
        explanation: 'Apostelgeschichte 20,9 – Eutychus schlief ein, fiel aus dem dritten Stock, wurde aber von Paulus wieder lebendig gemacht.',
      },
    ],
  },
  {
    id: 'default-gemischt-1',
    title: 'Bibel-Allgemeinwissen',
    category: 'Gemischt',
    description: 'Quer durch die ganze Bibel – für Fortgeschrittene',
    createdAt: 1700000009000,
    updatedAt: 1700000009000,
    questions: [
      {
        id: 'gm-q1',
        text: 'Wie viele Bücher hat die Bibel (protestantischer Kanon)?',
        answers: ['60', '66', '72', '78'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Die protestantische Bibel hat 66 Bücher: 39 im AT und 27 im NT.',
      },
      {
        id: 'gm-q2',
        text: 'Mit welchem Satz beginnt die Bibel?',
        answers: ['"Am Anfang schuf Gott Himmel und Erde."', '"In jenen Tagen..."', '"Ich bin der HERR, dein Gott."', '"Das Wort ward Fleisch."'],
        correct: 0,
        timeLimit: 15,
        explanation: '1. Mose 1,1 – "Im Anfang schuf Gott Himmel und Erde."',
      },
      {
        id: 'gm-q3',
        text: 'Welches ist das längste Buch der Bibel (nach Kapiteln)?',
        answers: ['Jesaja', 'Psalmen', '1. Könige', 'Matthäus'],
        correct: 1,
        timeLimit: 25,
        explanation: 'Das Buch der Psalmen hat 150 Kapitel und ist damit das längste Buch der Bibel.',
      },
      {
        id: 'gm-q4',
        text: 'Welcher König ließ die Bibel (das Gesetz) vorlesen, als er die Schriftrolle im Tempel fand?',
        answers: ['Hiskia', 'Josia', 'Salomo', 'David'],
        correct: 1,
        timeLimit: 25,
        explanation: '2. Könige 22 – König Josia ließ das Gesetzbuch vorlesen und löste eine Reform aus.',
      },
      {
        id: 'gm-q5',
        text: 'Wie lautet das erste der Zehn Gebote?',
        answers: ['"Du sollst nicht töten."', '"Du sollst nicht stehlen."', '"Du sollst keine anderen Götter neben mir haben."', '"Du sollst den Sabbat heiligen."'],
        correct: 2,
        timeLimit: 20,
        explanation: '2. Mose 20,3 – "Du sollst keine anderen Götter haben neben mir."',
      },
      {
        id: 'gm-q6',
        text: 'Welcher Vers wird oft als "das Evangelium im Kleinen" bezeichnet?',
        answers: ['Römer 8,28', 'Johannes 3,16', 'Psalm 23,1', 'Philipper 4,13'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Johannes 3,16 – "Denn so hat Gott die Welt geliebt..." wird oft "das Evangelium im Kleinen" genannt.',
      },
      {
        id: 'gm-q7',
        text: 'In welcher Stadt wurde Jesus geboren?',
        answers: ['Nazareth', 'Jerusalem', 'Bethanien', 'Bethlehem'],
        correct: 3,
        timeLimit: 15,
        explanation: 'Lukas 2,4-7 – Jesus wurde in Bethlehem geboren, der Stadt Davids.',
      },
      {
        id: 'gm-q8',
        text: 'Welches ist das letzte Buch der Bibel?',
        answers: ['Judas', 'Hebräer', 'Offenbarung', '1. Johannes'],
        correct: 2,
        timeLimit: 15,
        explanation: 'Die Offenbarung des Johannes ist das letzte Buch der Bibel.',
      },
    ],
  },
];
