import { QuizSet } from './quiz-types';

export const DEFAULT_QUIZ_SETS: QuizSet[] = [
  {
    id: 'default-at-1',
    title: 'Altes Testament Klassiker',
    category: 'AT',
    description: 'Bekannte Geschichten und Verse aus dem Alten Testament',
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
    questions: [
      {
        id: 'at-q1',
        text: 'Was war die erste Plage, die Gott über Ägypten schickte?',
        answers: ['Wasser wurde zu Blut', 'Frösche', 'Heuschrecken', 'Finsternis'],
        correct: 0,
        timeLimit: 20,
        explanation: '2. Mose 7,20 – Das Wasser des Nils wurde zu Blut.',
      },
      {
        id: 'at-q2',
        text: 'Wie viele Tage und Nächte regnete es während der Sintflut?',
        answers: ['20 Tage', '30 Tage', '40 Tage', '7 Tage'],
        correct: 2,
        timeLimit: 20,
        explanation: '1. Mose 7,4 – Es regnete 40 Tage und 40 Nächte.',
      },
      {
        id: 'at-q3',
        text: 'Womit erschlug David den Riesen Goliat?',
        answers: ['Mit einem Schwert', 'Mit einem Speer', 'Mit einem Stein und einer Schleuder', 'Mit einem Bogen'],
        correct: 2,
        timeLimit: 20,
        explanation: '1. Samuel 17,49 – David nahm einen Stein und schleuderte ihn.',
      },
      {
        id: 'at-q4',
        text: 'In welcher Stadt wurde der Tempel Salomos gebaut?',
        answers: ['Bethlehem', 'Nazareth', 'Jericho', 'Jerusalem'],
        correct: 3,
        timeLimit: 20,
        explanation: '1. Könige 6,1 – Salomo baute den Tempel in Jerusalem.',
      },
      {
        id: 'at-q5',
        text: 'Wer wurde in die Löwengrube geworfen, weil er trotz Verbot betete?',
        answers: ['Esra', 'Nehemia', 'Daniel', 'Hesekiel'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Daniel 6 – Daniel betete täglich und wurde in die Löwengrube geworfen.',
      },
    ],
  },
  {
    id: 'default-nt-1',
    title: 'Neues Testament Grundlagen',
    category: 'NT',
    description: 'Wichtige Ereignisse und Lehren aus dem Neuen Testament',
    createdAt: 1700000001000,
    updatedAt: 1700000001000,
    questions: [
      {
        id: 'nt-q1',
        text: 'Wie viele Jünger berief Jesus in seinen engsten Kreis?',
        answers: ['10', '12', '7', '24'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Matthäus 10,1 – Jesus berief seine zwölf Jünger.',
      },
      {
        id: 'nt-q2',
        text: 'Wer taufte Jesus im Jordan?',
        answers: ['Petrus', 'Andreas', 'Johannes der Täufer', 'Zacharias'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Matthäus 3,13-16 – Johannes der Täufer taufte Jesus im Jordan.',
      },
      {
        id: 'nt-q3',
        text: 'Welches Wunder vollbrachte Jesus bei der Hochzeit zu Kana?',
        answers: ['Er heilte einen Blinden', 'Er verwandelte Wasser in Wein', 'Er weckte einen Toten auf', 'Er stilte den Sturm'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Johannes 2,1-11 – Jesus verwandelte Wasser in Wein – sein erstes Wunder.',
      },
      {
        id: 'nt-q4',
        text: 'Auf welchem Berg hielt Jesus die Bergpredigt?',
        answers: ['Ölberg', 'Berg Tabor', 'Sinai', 'Ein namentloser Berg in Galiläa'],
        correct: 3,
        timeLimit: 20,
        explanation: 'Matthäus 5,1 – Jesus stieg auf einen Berg in Galiläa.',
      },
      {
        id: 'nt-q5',
        text: 'Was sagte Pontius Pilatus, nachdem er Jesus unschuldig befunden hatte?',
        answers: ['"Er ist schuldig!"', '"Ich wasche meine Hände in Unschuld."', '"Kreuzigt ihn sofort!"', '"Lasst ihn frei."'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Matthäus 27,24 – Pilatus wusch seine Hände als Zeichen seiner Unschuld.',
      },
    ],
  },
  {
    id: 'default-evangelien-1',
    title: 'Die vier Evangelien',
    category: 'Evangelien',
    description: 'Fragen zu den Gleichnissen und Wundern Jesu in den Evangelien',
    createdAt: 1700000002000,
    updatedAt: 1700000002000,
    questions: [
      {
        id: 'ev-q1',
        text: 'In welchem Gleichnis kehrt ein verlorener Sohn reumütig zu seinem Vater zurück?',
        answers: ['Gleichnis vom verlorenen Schaf', 'Gleichnis vom verlorenen Sohn', 'Gleichnis vom Sämann', 'Gleichnis von den Talenten'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Lukas 15,11-32 – Das Gleichnis vom verlorenen Sohn (dem verlorenen Sohn).',
      },
      {
        id: 'ev-q2',
        text: 'Wie viele Menschen speiste Jesus mit fünf Broten und zwei Fischen?',
        answers: ['1.000 Männer', '3.000 Menschen', '5.000 Männer', '10.000 Menschen'],
        correct: 2,
        timeLimit: 20,
        explanation: 'Matthäus 14,21 – Es aßen etwa 5.000 Männer, ohne Frauen und Kinder.',
      },
      {
        id: 'ev-q3',
        text: 'Wen erweckte Jesus in Bethanien von den Toten?',
        answers: ['Jairus', 'Lazarus', 'Stephanus', 'Zachäus'],
        correct: 1,
        timeLimit: 20,
        explanation: 'Johannes 11 – Jesus erweckte Lazarus, den Bruder von Maria und Marta.',
      },
      {
        id: 'ev-q4',
        text: 'Mit welchem Satz beginnt das Johannesevangelium?',
        answers: ['"Im Anfang war das Wort."', '"Ein Buch der Geschichte Jesu Christi."', '"In jenen Tagen kam Johannes der Täufer."', '"Es begab sich aber zu der Zeit."'],
        correct: 0,
        timeLimit: 20,
        explanation: 'Johannes 1,1 – "Im Anfang war das Wort, und das Wort war bei Gott."',
      },
      {
        id: 'ev-q5',
        text: 'Welcher Jünger verneinte Jesus dreimal, bevor der Hahn krähte?',
        answers: ['Judas', 'Johannes', 'Thomas', 'Petrus'],
        correct: 3,
        timeLimit: 20,
        explanation: 'Lukas 22,60-61 – Petrus verneinte Jesus dreimal, wie Jesus es vorausgesagt hatte.',
      },
    ],
  },
];
